### ISSUE TITLE
Help to connect SEL351R recloser to Rpi3

### ISSUE THREAD

**Issue by Kartheek1512** [automatak/pifacertu#2]
Hi, 

 I am planning on retrieving data from SEL 351R recloser periodically. I want to use Raspberry pi3 as a master. I saw in the SEL 351R manual that it communicates via DNP3 protocol.  I have used node-red before on Rpi3 and did modbus communications. But I am new to this DNP3 protocol. Do you have any videos or instructions to help me.

**Comment by jadamcrain** [comment]
Hi,

You'll want to start with just the core opendnp3 library:

https://www.automatak.com/opendnp3/

Send any questions to the forum (link at top of page).

Compiling it and changing the IP / link addresses in the master example would be a good place to start:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/examples/master/main.cpp

-Adam
