### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Malwaremamu** [automatak/pifacertu#3]
33%] Building CXX object CMakeFiles/pifacertu.dir/PifaceIOHandler.cpp.o
In file included from /home/pi/Desktop/pifacertu/PifaceIOHandler.cpp:1:0:
/home/pi/Desktop/pifacertu/PifaceIOHandler.h:5:49: fatal error: opendnp3/outstation/ICommandHandler.h: No such file or directory
 #include <opendnp3/outstation/ICommandHandler.h>
                                                 ^
compilation terminated.
CMakeFiles/pifacertu.dir/build.make:62: recipe for target 'CMakeFiles/pifacertu.dir/PifaceIOHandler.cpp.o' failed
make[2]: *** [CMakeFiles/pifacertu.dir/PifaceIOHandler.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pifacertu.dir/all' failed
make[1]: *** [CMakeFiles/pifacertu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can you tell me what is the error?

I am trying to communicate dnp3 pifacertu on rpi with other rpi as Master and slave communication. Do you have any suggestions or recommendations for this?

**Comment by jadamcrain** [comment]
It can't find the opendnp3 headers. Have you built and installed opendnp3 2.1.0?

https://github.com/automatak/pifacertu#building
