### ISSUE TITLE
Few Doubts or Questions

### ISSUE THREAD

**Issue by Malwaremamu** [automatak/pifacertu#4]
Hi, I am new to RPI and DNP3. I got few questions building a power grid with Rpi model 3 running raspbian stretch(New Release which is offered by RPI.org). 
I am trying to install DNP3 from automatak/dnp3.git. But I am facing problems such as JNI, C++ and others.
1. Can you please mention what packages with versions do we need to install for raspbian stretch or can we run on Noobs Version running on rpi model 3.
2. After installing Piface, Do I need to connect my RPI3 with piface board (or) can I connect with another RPI3. 

I am waiting for your reply. If I am successful with building a DNP3 with Piface, I will make a video with detail description with your credits. 
I am building this for my research.

Thank you in advance.

**Comment by jadamcrain** [comment]
Hi @Malwaremamu,

1) 

On a Debian distribution, you probably just need:

```
>sudo apt install g++ cmake git
```
2) 

To run the pifacertu executable in this repository, you must have the piface board installed. However, the base opendnp3 project comes with several demos that don't interact with any hardware and work on any Linux. You can build them using -DDNP3_DEMO=ON when initializing cmake.

Feel free to send any further questions to the mailing list and hopefully we can get you going. I'd definitely get opendnp3 installing and the basic demos running, before attempting to build the piface demo which uses the library.

-Adam
