### ISSUE TITLE
compiling error in asiopal

### ISSUE THREAD

**Issue by JoseAurelioPorto** [automatak/pifacertu#5]
I am trying build ASIOPAL e ASIODNP3 and i am gettin  an compiling error in EXECUTOR.H  when declaring asio::satrnd strand:

1>C:\Projects\dnp3open\.\cpp\libs\include\asiopal/Executor.h(84): error C2955: 'asio::strand': use of class template requires template argument list
This is a part of  include file:

 */
#ifndef ASIOPAL_EXECUTOR_H
#define ASIOPAL_EXECUTOR_H

#include <openpal/executor/IExecutor.h>
#include <openpal/util/Uncopyable.h>

#include "asiopal/IO.h"
#include "asiopal/SteadyClock.h"

#include <future>

namespace asiopal
{

/**
*
* Implementation of openpal::IExecutor backed by asio::strand
*
* Shutdown life-cycle guarantees are provided by using std::shared_ptr
*
*/
class Executor final :
		public openpal::IExecutor,
		public std::enable_shared_from_this<Executor>,
		private openpal::Uncopyable
{

public:

	Executor(const std::shared_ptr<IO>& io);

	static std::shared_ptr<Executor> Create(const std::shared_ptr<IO>& io)
	{
		return std::make_shared<Executor>(io);
	}

	/// ---- Implement IExecutor -----

	virtual openpal::MonotonicTimestamp GetTime() override;
	virtual openpal::ITimer* Start(const openpal::TimeDuration&, const openpal::action_t& runnable)  override;
	virtual openpal::ITimer* Start(const openpal::MonotonicTimestamp&, const openpal::action_t& runnable)  override;
	virtual void Post(const openpal::action_t& runnable) override;

	template <class T>
	T ReturnFrom(const std::function<T()>& action);

	void BlockUntil(const std::function<void ()>& action);

	void BlockUntilAndFlush(const std::function<void()>& action);

private:

	// we hold a shared_ptr to the pool so that it cannot dissapear while the strand is still executing
	std::shared_ptr<IO> io;

public:

	// Create a new Executor that shares the underling std::shared_ptr<IO>
	std::shared_ptr<Executor> Fork() const
	{
		return Create(this->io);
	}

	asio::strand strand;

private:

	openpal::ITimer* Start(const steady_clock_t::time_point& expiration, const openpal::action_t& runnable);

};

**Comment by jadamcrain** [comment]
My guess is that newer versions of ASIO have made asio::strand a template, whereas in previous versions it was not. You might try using the same release tag that opendnp3 uses:

https://github.com/automatak/dnp3/tree/2.0.x/deps

**Comment by JoseAurelioPorto** [comment]
Dear Adam

 

You get the exact target: It Works very good now. 

Thank you very much!!!

 

Atenciosamente

 



José Aurélio Pôrto 
Diretor Técnico
+55 61 99223 1755
Skype: joseaporto4205

Parque Capital Digital, 04 - Parte 1 andar
70635-815 - Granja do Torto - Brasilia DF

 

 <tel:%2B55%2061%203340%208486> +55 61 3340 8486
 <http://www.spinengenharia.com.br/> www.spinengenharia.com.br

 

 

 

De: Adam Crain <notifications@github.com> 
Enviada em: quinta-feira, 9 de maio de 2019 18:05
Para: automatak/pifacertu <pifacertu@noreply.github.com>
Cc: JoseAurelioPorto <porto@spinengenharia.com.br>; Author <author@noreply.github.com>
Assunto: Re: [automatak/pifacertu] compiling error in asiopal (#5)

 

My guess is that newer versions of ASIO have made asio::strand a template, whereas in previous versions it was not. You might try using the same release tag that opendnp3 uses:

https://github.com/automatak/dnp3/tree/2.0.x/deps

**Comment by jadamcrain** [comment]
Great, glad I could help.
