### ISSUE TITLE
1>LINK : fatal error LNK1181: cannot open input file 'libeay32MD.lib'

### ISSUE THREAD

**Issue by JoseAurelioPorto** [automatak/pifacertu#6]
Now trying to build DNp3CLRAdapter   getting a link error:
1>------ Build started: Project: DNP3CLRAdapter, Configuration: Release x64 ------
1>LINK : fatal error LNK1181: cannot open input file 'libeay32MD.lib'
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

I already install boths OpenSSL 32 and 64. In fact inside libs directories there arent this libs.

![image](https://user-images.githubusercontent.com/50031830/57538570-1715dd00-731f-11e9-8cbf-cc9f2400a18b.png)

**Comment by jadamcrain** [comment]
I believe this is a difference between openssl versions. previous versions called the libraries different names.

Which version did you install? Let me know and I can open a ticket for the opendnp3 project to migrate the C# build to the newer openssl release.

See this:

https://github.com/arvidn/libtorrent/issues/1931

**Comment by JoseAurelioPorto** [comment]
Adam

I downloaded this file fWin32OpenSSL-1_1_0j.exe. from Shinning Light.

 

I downloaded the files required by current opendnp3 and already build successfully software, and start testing Client example.

 

By the way, do you have some C# example source code showing how to get the data and identify it, after receiving an response to a Class 0 Scan?

 

 

Atenciosamente

 



José Aurélio Pôrto 
Diretor Técnico
+55 61 99223 1755
Skype: joseaporto4205

Parque Capital Digital, 04 - Parte 1 andar
70635-815 - Granja do Torto - Brasilia DF

 

 <tel:%2B55%2061%203340%208486> +55 61 3340 8486
 <http://www.spinengenharia.com.br/> www.spinengenharia.com.br

 

 

 

De: Adam Crain <notifications@github.com> 
Enviada em: sábado, 11 de maio de 2019 19:59
Para: automatak/pifacertu <pifacertu@noreply.github.com>
Cc: JoseAurelioPorto <porto@spinengenharia.com.br>; Author <author@noreply.github.com>
Assunto: Re: [automatak/pifacertu] 1>LINK : fatal error LNK1181: cannot open input file 'libeay32MD.lib' (#6)

 

I believe this is a difference between openssl versions. previous versions called the libraries different names.

Which version did you install? Let me know and I can open a ticket for the opendnp3 project to migrate the C# build to the newer openssl release.

**Comment by jadamcrain** [comment]
https://github.com/automatak/dnp3/tree/2.0.x/dotnet/examples

Let's move any further discussion about opendnp3 to the mailing list:

https://groups.google.com/forum/#!forum/automatak-dnp3
